name: "Custom GitHub Action"
description: "Custom GitHub Action"
inputs:
  terraform_env_variables:
    description: "List of Terraform Environmental Variables"
    required: true
runs:
  using: "composite"
  steps:
    - name: Export Terraform Environmental Variables
      run: |
        terraform_env_variables=$(cat <<EOF
        ${{ inputs.terraform_env_variables }}
        EOF
        )

        echo loop
        echo "$terraform_env_variables" | while read line; do
          echo export $line
          echo $line >> $GITHUB_ENV 
        done
      shell: bash
    - name: Check Terraform Environmental Variables
      run: |
        echo $TF_CLI_ARGS_init
      shell: bash
    - name: Check Terraform Environmental Variables
      run: |
        echo $TF_VAR_aws_account_id
      shell: bash
